[package]
name = "troglodyt"
version = "0.1.0"
edition = "2024"


[dependencies]
anyhow = "1.0.98"
bon = "3.6.4"
md5 = "0.8.0"
rustix = { version = "1.0.7", features = ["rand"] }
shrinkwraprs = "0.3.0"
xcb = "1.5.0"
